<?php
 
$this->headTitle('My Blog');

$this->placeholder('sidebar')
      ->setPrefix("<div class=\"sidebar-box\">\n")
      ->setSeparator("\n</div>\n<div class=\"sidebar-box\">\n")
      ->setPostfix("\n</div>")
      ->setIndent(8);

echo '<?xml version="1.0" encoding="UTF-8" ?>';
?> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <?php echo $this->headTitle(); ?> 
    <?php echo $this->headLink(); ?> 
    <?php echo $this->headScript(); ?> 
</head>

<body>
    <div id="page-title">
        <h1><a href="<?php echo $this->baseUrl ?>">My Blog</a></h1>

<?php if ($this->identity): ?>
        <div id="page-title-toolbox">
            <a href="<?php echo $this->baseUrl ?>/new-post">new post</a> |
            <a href="<?php echo $this->baseUrl ?>/user/logout">log out</a>
        </div>
<?php endif; ?>

        <h3>I have some original thoughts too!</h3>
    </div>
    
    <div id="page-content">
        <?php echo $this->layout()->content ?> 
    </div>
    
    <div id="page-sidebar">
        <?php echo $this->placeholder('sidebar'); ?> 
    </div>
    
    <div id="page-footer">
        <p> 
            All content is &copy; copyright 2009 Evil Corporation INC.<br />
            By posting you agree that your soul belongs to Satan
        </p>
        <p>
            Powered by Stoa ver. 0.1; get Stoa: <a href="http://github.com/shevron/stoa">http://github.com/shevron/stoa</a>
        </p>
        <p>
            <a href="<?php echo $this->baseUrl ?>/user/login">administrator log-in</a>
        </p>
    </div>
</body>

</html>
